#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ignition.Resource", IsApplication=true)]

namespace Ignition
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Refractored.Fab.Resource.Attribute.fab_colorDisabled = global::Ignition.Resource.Attribute.fab_colorDisabled;
			global::Refractored.Fab.Resource.Attribute.fab_colorNormal = global::Ignition.Resource.Attribute.fab_colorNormal;
			global::Refractored.Fab.Resource.Attribute.fab_colorPressed = global::Ignition.Resource.Attribute.fab_colorPressed;
			global::Refractored.Fab.Resource.Attribute.fab_colorRipple = global::Ignition.Resource.Attribute.fab_colorRipple;
			global::Refractored.Fab.Resource.Attribute.fab_shadow = global::Ignition.Resource.Attribute.fab_shadow;
			global::Refractored.Fab.Resource.Attribute.fab_size = global::Ignition.Resource.Attribute.fab_size;
			global::Refractored.Fab.Resource.Attribute.layoutManager = global::Ignition.Resource.Attribute.layoutManager;
			global::Refractored.Fab.Resource.Attribute.reverseLayout = global::Ignition.Resource.Attribute.reverseLayout;
			global::Refractored.Fab.Resource.Attribute.spanCount = global::Ignition.Resource.Attribute.spanCount;
			global::Refractored.Fab.Resource.Attribute.stackFromEnd = global::Ignition.Resource.Attribute.stackFromEnd;
			global::Refractored.Fab.Resource.Color.fab_material_blue_500 = global::Ignition.Resource.Color.fab_material_blue_500;
			global::Refractored.Fab.Resource.Dimension.fab_elevation_lollipop = global::Ignition.Resource.Dimension.fab_elevation_lollipop;
			global::Refractored.Fab.Resource.Dimension.fab_scroll_threshold = global::Ignition.Resource.Dimension.fab_scroll_threshold;
			global::Refractored.Fab.Resource.Dimension.fab_shadow_size = global::Ignition.Resource.Dimension.fab_shadow_size;
			global::Refractored.Fab.Resource.Dimension.fab_size_mini = global::Ignition.Resource.Dimension.fab_size_mini;
			global::Refractored.Fab.Resource.Dimension.fab_size_normal = global::Ignition.Resource.Dimension.fab_size_normal;
			global::Refractored.Fab.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::Ignition.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::Refractored.Fab.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::Ignition.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::Refractored.Fab.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::Ignition.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::Refractored.Fab.Resource.Drawable.fab_shadow = global::Ignition.Resource.Drawable.fab_shadow;
			global::Refractored.Fab.Resource.Drawable.fab_shadow_mini = global::Ignition.Resource.Drawable.fab_shadow_mini;
			global::Refractored.Fab.Resource.Id.item_touch_helper_previous_elevation = global::Ignition.Resource.Id.item_touch_helper_previous_elevation;
			global::Refractored.Fab.Resource.Id.mini = global::Ignition.Resource.Id.mini;
			global::Refractored.Fab.Resource.Id.normal = global::Ignition.Resource.Id.normal;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton = global::Ignition.Resource.Styleable.FloatingActionButton;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::Ignition.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::Ignition.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::Ignition.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::Ignition.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::Ignition.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_size = global::Ignition.Resource.Styleable.FloatingActionButton_fab_size;
			global::Refractored.Fab.Resource.Styleable.RecyclerView = global::Ignition.Resource.Styleable.RecyclerView;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_android_descendantFocusability = global::Ignition.Resource.Styleable.RecyclerView_android_descendantFocusability;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_android_orientation = global::Ignition.Resource.Styleable.RecyclerView_android_orientation;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_layoutManager = global::Ignition.Resource.Styleable.RecyclerView_layoutManager;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_reverseLayout = global::Ignition.Resource.Styleable.RecyclerView_reverseLayout;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_spanCount = global::Ignition.Resource.Styleable.RecyclerView_spanCount;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_stackFromEnd = global::Ignition.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int fab_colorDisabled = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int fab_colorNormal = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int fab_colorPressed = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fab_colorRipple = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fab_shadow = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int fab_size = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int fab_material_blue_500 = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050007
			public const int fab_elevation_lollipop = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int fab_scroll_threshold = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int fab_shadow_size = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int fab_size_mini = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int fab_size_normal = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int item_touch_helper_swipe_escape_max_velocity = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int item_touch_helper_swipe_escape_velocity = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_shadow_mini = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int addButton = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int llout = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int mini = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int myButton = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int normal = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080002
			public const int add = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
